services:
  php:
    image: php:7.4.15-apache
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./php:/var/www/html

  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: php_essentials
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
